"""empty message

Revision ID: 2aa522b31690
Revises: 8af49ac15963
Create Date: 2018-07-31 15:16:39.521688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa522b31690'
down_revision = '8af49ac15963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api_group',
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(length=255), nullable=False),
    sa.Column('parentGroupID', sa.Integer(), nullable=False),
    sa.Column('isChild', sa.Boolean(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectID'], ['eo_project.projectID'], ),
    sa.PrimaryKeyConstraint('groupID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_group')
    # ### end Alembic commands ###
