"""empty message

Revision ID: 4fb72080914a
Revises: e8ee14515d86
Create Date: 2018-08-03 10:59:51.900310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb72080914a'
down_revision = 'e8ee14515d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api_request_value',
    sa.Column('valueID', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('paramID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paramID'], ['eo_api_request_param.paramID'], ),
    sa.PrimaryKeyConstraint('valueID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_request_value')
    # ### end Alembic commands ###
