"""empty message

Revision ID: 9c07926ac72e
Revises: 2aa522b31690
Create Date: 2018-08-02 14:09:36.673584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c07926ac72e'
down_revision = '2aa522b31690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_api',
    sa.Column('apiID', sa.Integer(), nullable=False),
    sa.Column('apiName', sa.String(length=100), nullable=False),
    sa.Column('apiURI', sa.String(length=100), nullable=False),
    sa.Column('apiProtocol', sa.Boolean(), nullable=False),
    sa.Column('apiFailureMock', sa.Text(), nullable=True),
    sa.Column('apiSuccessMock', sa.Text(), nullable=True),
    sa.Column('apiRequestType', sa.Boolean(), nullable=False),
    sa.Column('apiSuccessMockType', sa.Boolean(), nullable=False),
    sa.Column('apiFailureMockType', sa.Boolean(), nullable=False),
    sa.Column('apiStatus', sa.Boolean(), nullable=False),
    sa.Column('apiUpdateTime', sa.DateTime(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('removeTime', sa.DateTime(), nullable=True),
    sa.Column('apiNoteType', sa.Boolean(), nullable=False),
    sa.Column('apiNoteRaw', sa.Text(), nullable=True),
    sa.Column('apiRequestParamType', sa.Boolean(create_constraint=3), nullable=False),
    sa.Column('apiRequestRaw', sa.Text(), nullable=True),
    sa.Column('updateUserId', sa.Integer(), nullable=False),
    sa.Column('apiSuccessStatusCode', sa.String(length=255), nullable=True),
    sa.Column('apiFailureStatusCode', sa.String(length=255), nullable=True),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.Column('projectID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupID'], ['eo_api_group.groupID'], ),
    sa.ForeignKeyConstraint(['projectID'], ['eo_project.projectID'], ),
    sa.PrimaryKeyConstraint('apiID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api')
    # ### end Alembic commands ###
