"""empty message

Revision ID: d4b983612f6d
Revises: 
Create Date: 2018-07-17 10:53:11.247479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b983612f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_project',
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.Column('projectType', sa.Integer(), nullable=False),
    sa.Column('projectName', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('projectCreateTime', sa.DateTime(), nullable=False),
    sa.Column('projectUpdateTime', sa.DateTime(), nullable=False),
    sa.Column('projectVersion', sa.String(length=6, collation='utf8_bin'), nullable=False),
    sa.PrimaryKeyConstraint('projectID')
    )
    op.create_table('eo_api_env',
    sa.Column('envID', sa.Integer(), nullable=False),
    sa.Column('envName', sa.String(length=255), nullable=False),
    sa.Column('envDesc', sa.String(length=255), nullable=True),
    sa.Column('projectID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectID'], ['eo_project.projectID'], ),
    sa.PrimaryKeyConstraint('envID')
    )
    op.create_table('eo_api_env_front_uri',
    sa.Column('uriID', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('applyProtocol', sa.String(length=4), nullable=True),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('uriID')
    )
    op.create_table('eo_api_env_header',
    sa.Column('headerID', sa.Integer(), nullable=False),
    sa.Column('headerName', sa.String(length=255), nullable=False),
    sa.Column('headerValue', sa.String(length=255), nullable=False),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('headerID')
    )
    op.create_table('eo_api_env_param',
    sa.Column('paramID', sa.Integer(), nullable=False),
    sa.Column('paramKey', sa.String(length=255), nullable=False),
    sa.Column('paramValue', sa.String(length=255), nullable=False),
    sa.Column('paramDesc', sa.String(length=255), nullable=True),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('paramID')
    )
    op.create_table('eo_api_env_param_additional',
    sa.Column('paramID', sa.Integer(), nullable=False),
    sa.Column('paramKey', sa.String(length=255), nullable=False),
    sa.Column('paramValue', sa.String(length=255), nullable=False),
    sa.Column('paramDesc', sa.String(length=255), nullable=True),
    sa.Column('envID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['envID'], ['eo_api_env.envID'], ),
    sa.PrimaryKeyConstraint('paramID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_api_env_param_additional')
    op.drop_table('eo_api_env_param')
    op.drop_table('eo_api_env_header')
    op.drop_table('eo_api_env_front_uri')
    op.drop_table('eo_api_env')
    op.drop_table('eo_project')
    # ### end Alembic commands ###
